creds: "insert-your-creds"
model: "GigaChat-Pro"

system_prompt_news_path: "prompts/system_prompt_news.txt"
system_prompt_path: "prompts/system_prompt.txt"

prompt_path: "prompts/prompt.txt"

type_of_news_path: "prompts/types_of_news.txt"
